### PR TITLE
Fine with 10 failures

### PR DESCRIPTION
**Pull request by captn3m0**
Filed on the wrong repo, but I'll leave this open regardless.

This PR adds 2 things:

1. Fixes DEPLOYMENT_GET error reporting
2. Allows for 10 failures in DEPLOYMENT_GET. We've noticed AWS CD API timing out on that call, and it made sense to wait till 10 errors before giving up.

### CODE REVIEW

**Comment by captn3m0** [comment]
If anyone is facing the same issues, this is now published as a wercker step: https://app.wercker.com/applications/58f9e2827ce0fb01007c6419/tab/details/

**Comment by captn3m0** [comment]
Doesn't look like this is going to get merged.

**Comment by jazzmind** [comment]
@captn3m0  hey - I didn't realise I even had this fork of the repo, sorry for not spotting the PRs... 
did you merge to hashfyre's repo?

**Comment by captn3m0** [comment]
Merged this to https://github.com/razorpay/wercker-aws-code-deploy, which is published at https://app.wercker.com/applications/58f9e2827ce0fb01007c6419/tab/details/. (I work with @hashfyre at @Razorpay, so we maintain a organization fork)

**Pull request closed without merging**
